# Generated by Django 4.2.7 on 2023-12-16 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='createdBy',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='drink',
            old_name='createdOn',
            new_name='created_on',
        ),
    ]
