# Generated by Django 4.2.7 on 2023-12-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0002_drink_createdby'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='is_publishable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='drink',
            name='uuid',
            field=models.CharField(default=' ', max_length=5),
        ),
    ]
