# Generated by Django 4.2.7 on 2023-12-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0003_drink_is_publishable_drink_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='uuid',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
