# Generated by Django 4.2.7 on 2023-12-24 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0003_rename_createdby_drink_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drink',
            options={'ordering': ('created_on',)},
        ),
        migrations.CreateModel(
            name='DrinkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='drinks.drink')),
            ],
        ),
    ]
